id: P766B7496
initial_creation_type: input
source_metadata:
  title: Tashi Tobgyal
  language: bo
  description: Tashi Tobgyal (bkra shis stobs rgyal, 1550?–1603) is an important figure
    in the lineage of the Northern Treasures (byang gter). He was the reincarnation
    of Ngari Paṇchen Pema Wangyel (1487–1542) and the father of Rigdzin Ngakgi Wangpo
    (1580–1639), who founded the monastery of Dorje Drak.
  volume:
    c9e1fc8b17e14d188a36b19916dbc908:
      title: 'A Stream of Blessing: Verses of Supplication to the Accomplished Holders
        of Mantra who Gained Realization in this Snowy Land of Tibet'
      parent: Prayers
created_at: '2022-03-01T01:40:13.298059'
last_modified_at: '2022-03-01T01:40:13.298062'
statistics:
  total_words: 755
  total_non_words: 47
quality:
  non_words_ratio: 0.06
